# CREAR Y CONECTAR BASE DE DATOS MARIADB: 

# CREAR BASE DE DATOS EN XAMPP CON PHPMYADMIN


# CONECTAR BASE DE DATOS:

# COMO VAMOS A USAR MARIADB COMO GESTOR, TENEMOS QUE HACER UN PIP INSTALL MARIADB

# DESPUES TENEMOS QUE IMPORTAR

import mariadb
import sys


# VAMOS A METER TODO EL CODIGO DE CONEXION A BASE DE DATOS EN TKINTER
import tkinter as tk

root = tk.Tk()
root.title("Ventana principal")
root.geometry("300x200")

# GUARDAR LOS PARAMETROS DE CONEXION EN UNA VARIABLE, CON UN BLOQUE TRY EXCEPT POR SI HAY ERRORES

try:
    conexion = mariadb.connect(
        user="root", # => EN "user='x'", PONEMOS EL NOMBRE DE USUARIO DE NUESTRA BASE DE DATOS
        password="", # => EN "password='x'", PONEMOS LA CONTRASEÑA DE NUESTRO USUARIO, EN ESTE CASO COMO ROOT NO TIENE CONTRASÑEA DE DEJA VACIO
        host="127.0.0.1",  # => EN "host='xyz.x.y.z'", PONEMOS EL HOST, EN ESTE CASO COMO ES UN SERVIDOR LOCAL SE PONE LA IP LOCAL
        port=3306, # => PUERTO POR DEFECTO ES 3306 EN DIFERENTES ZONAS PUEDE CAMBIAR DE 06 A 07
        database="prueba" # => EN "database='nombre_database'", PONEMOS EL NOMBRE DE LA BASE DE DATOS A LA CUAL NOS QUEREMOS CONECTAR
    )
except mariadb.Error as error:
    print(f"Error al conectar con la base de datos: {error}")
    sys.exit(1) # => SE TIENE QUE IMPORTAR LA LIBRERIA .SYS Y USAR EL METODO .EXIT(1), PARA QUE AL MOMENTO QUE SE ENCUENTRE UN ERROR NO LANCE EL PROGRAMA



root.mainloop()


# ESTA FORMA ES ANTICUADA PORQ AHORA NO PERMITE IMPORTAR MARIADB, EN LUGAR DE ESTO VE AL SIGUIENTE ARCHIVO "crear_tablas_mariadb.py", PARA VER UNA MEJOR FORMA :)